name: q_note
description: Q Note
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.7.0
  loading_animation_widget: ^1.2.0+4
  firebase_core: ^2.15.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^5.1.0
  flutter_otp_text_field: ^1.1.1
  firebase_auth: ^4.7.3
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.8.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_screen/
    - assets/images/on_boarding_image/
    - assets/images/welcome_images/
    - assets/images/login_screen_image/
    - assets/images/dashboard_images/
    - assets/images/logo/

  fonts:
    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-Light.ttf

    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: fonts/Poppins-Black.ttf